server:
  port: 8080
spring:
  application.name: feign

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  #Feign自带断路器,需要配置开启
  hystrix.enabled: true
  #启动httpclient，主要使用线程池
  httpclient.enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

endpoints:
  shutdown:
    #启用shutdown
    enabled: true
    #禁用密码验证
    sensitive: false